// Generated by CoffeeScript 1.10.0
var Task, merge, serverOpts, startSelenium, startServer;

startSelenium = require("./start");

startServer = require("./serve");

Task = require('ember-cli/lib/models/task');

merge = require('lodash/object').merge;

serverOpts = {
  port: 4200,
  insecureProxy: false,
  watcher: "events",
  liveReload: false,
  ssl: false,
  sslKey: "ssl/server.key",
  sslCert: "ssl/server.crt"
};

module.exports = Task.extend({
  run: function(opts) {
    return startSelenium.run(opts).then(function(selenium) {
      return startServer.run(merge(serverOpts, opts)).then(function() {
        return selenium.finishBuild();
      });
    });
  }
});
