// Generated by CoffeeScript 1.10.0
var RSVP, ServeEmber, StartBrowser, Task, assign, merge, serverOpts;

StartBrowser = require("./start-browser");

ServeEmber = require("./serve-ember");

Task = require('ember-cli/lib/models/task');

merge = require('lodash/object').merge;

RSVP = require('rsvp');

assign = require('lodash/assign');

serverOpts = {
  insecureProxy: false,
  watcher: "events",
  liveReload: false,
  ssl: false,
  sslKey: "ssl/server.key",
  sslCert: "ssl/server.crt"
};

module.exports = Task.extend({
  run: function(browserOptions) {
    var commandOptions, serve, start;
    start = new StartBrowser({
      ui: this.ui,
      analytics: this.analytics,
      project: this.project
    });
    serve = new ServeEmber({
      ui: this.ui,
      analytics: this.analytics,
      project: this.project
    });
    commandOptions = assign(serverOpts, browserOptions, {
      baseURL: this.project.config(browserOptions.environment).baseURL || '/'
    });
    return RSVP.hash({
      browser: start.run(browserOptions),
      server: serve.run(commandOptions)
    }).then(function(arg) {
      var browser;
      browser = arg.browser;
      return browser.buildPages();
    });
  }
});
