// Generated by CoffeeScript 1.10.0
var Builder, ExpressServer, LiveReloadServer, Promise, ServerWatcher, Task, Watcher, existsSync, path;

existsSync = require('exists-sync');

path = require('path');

LiveReloadServer = require('ember-cli/lib/tasks/server/livereload-server');

ExpressServer = require('ember-cli/lib/tasks/server/express-server');

Promise = require('ember-cli/lib/ext/promise');

Task = require('ember-cli/lib/models/task');

Watcher = require('ember-cli/lib/models/watcher');

Builder = require('ember-cli/lib/models/builder');

ServerWatcher = require('ember-cli/lib/models/server-watcher');

module.exports = Task.extend({
  run: function(options) {
    var builder, expressServer, serverRoot, serverWatcher, watcher;
    builder = new Builder({
      ui: this.ui,
      outputPath: options.outputPath,
      project: this.project,
      environment: options.environment
    });
    watcher = new Watcher({
      ui: this.ui,
      builder: builder,
      analytics: this.analytics,
      options: options
    });
    serverRoot = './server';
    if (existsSync(serverRoot)) {
      serverWatcher = new ServerWatcher({
        ui: this.ui,
        analytics: this.analytics,
        watchedDir: path.resolve(serverRoot)
      });
    } else {
      throw new Error("Missing server! ember-selenium-build didn't install right");
    }
    expressServer = new ExpressServer({
      ui: this.ui,
      project: this.project,
      watcher: watcher,
      serverRoot: serverRoot,
      serverWatcher: serverWatcher
    });
    return expressServer.start(options);
  }
});
