// Generated by CoffeeScript 1.10.0
var Machine, Task;

Task = require('ember-cli/lib/models/task');

Machine = require('../models/machine');

module.exports = Task.extend({
  run: function(arg) {
    var buildRoutes, flavor, outputPath;
    flavor = arg.flavor, outputPath = arg.outputPath, buildRoutes = arg.buildRoutes;
    return Machine.initialize({
      flavor: flavor,
      baseURI: "http://localhost:4200",
      outPath: outputPath,
      routes: buildRoutes
    });
  }
});
