// Generated by CoffeeScript 1.10.0
var Writer, fs, path;

path = require("path");

fs = require("fs-extra");

Writer = (function() {
  function Writer(arg) {
    var ref;
    this.stdout = arg.stdout, this.base = (ref = arg.base) != null ? ref : "";
  }

  Writer.prototype.write = function(fileContents) {
    this.fileContents = fileContents;
    return this;
  };

  Writer.prototype.intoFile = function(name) {
    var filename;
    filename = this.makeFileName(name);
    if (!this.stdout) {
      return fs.outputFileSync(filename, this.fileContents);
    } else {
      return {
        name: filename,
        content: this.fileContents
      };
    }
  };

  Writer.prototype.makeFileName = function(name) {
    return path.normalize(path.join(this.base, name + ".html"));
  };

  return Writer;

})();

module.exports = Writer;
