// Generated by CoffeeScript 1.10.0
var Writer, fs, path;

path = require("path");

fs = require("fs-extra");

Writer = (function() {
  function Writer(base) {
    this.base = base;
  }

  Writer.prototype.write = function(fileContents) {
    this.fileContents = fileContents;
    return this;
  };

  Writer.prototype.intoFile = function(name) {
    var filename;
    filename = this.makeFileName(name);
    return fs.outputFileSync(filename, this.fileContents);
  };

  Writer.prototype.makeFileName = function(name) {
    return path.normalize(path.join(this.base, name + ".html"));
  };

  return Writer;

})();

module.exports = Writer;
