// Generated by CoffeeScript 1.10.0
var SeleniumBuild;

SeleniumBuild = (function() {
  var instance;

  function SeleniumBuild() {}

  instance = null;

  SeleniumBuild.instance = function() {
    return instance;
  };

  return SeleniumBuild;

})();
