// Generated by CoffeeScript 1.10.0
var RSVP, asyncMap,
  slice = [].slice;

RSVP = require("rsvp");

asyncMap = function(xs, promiseF, output) {
  var first, rest;
  if (xs == null) {
    xs = [];
  }
  if (output == null) {
    output = [];
  }
  first = xs[0], rest = 2 <= xs.length ? slice.call(xs, 1) : [];
  if (xs.length === 0) {
    return new RSVP.Promise(function(resolve) {
      return resolve(output);
    });
  } else {
    return promiseF(first).then(function(result) {
      return asyncMap(rest, promiseF, output.concat(result));
    });
  }
};

module.exports = asyncMap;
