// Generated by CoffeeScript 1.10.0
var RSVP, exec, runCmd;

RSVP = require('rsvp');

exec = require("child_process").exec;

runCmd = function(cmd, opts) {
  return new RSVP.Promise(function(resolve, reject) {
    return exec(cmd, opts, function(err, stdout, stderr) {
      if (err != null) {
        return reject(err);
      }
      if (stdout != null) {
        console.log(stdout);
      }
      if (stderr != null) {
        console.log(stderr);
      }
      return resolve(stdout);
    });
  });
};

module.exports = runCmd;
