// Generated by CoffeeScript 1.10.0
var EnvOpt, FlavorOpt, HostOpt, OutOpt, PathOpt, PortOpt, Selenium, StdOpt, defaultPort, path;

Selenium = require("../tasks/selenium");

path = require("path");

defaultPort = process.env.PORT || 4200;

EnvOpt = {
  name: 'environment',
  type: String,
  "default": 'production',
  aliases: [
    'e', {
      'dev': 'development'
    }, {
      'prod': 'production'
    }
  ]
};

OutOpt = {
  name: 'output-path',
  type: 'Path',
  "default": 'selenium-dist/',
  aliases: ['op', 'out']
};

StdOpt = {
  name: "std-out",
  type: Boolean,
  "default": false
};

PathOpt = {
  name: 'build-routes',
  type: 'Path',
  "default": 'ember-selenium-build.js'
};

FlavorOpt = {
  name: "flavor",
  type: String,
  "default": "chrome"
};

HostOpt = {
  name: "host",
  type: String,
  "default": "localhost"
};

PortOpt = {
  name: "port",
  type: Number,
  "default": defaultPort
};

module.exports = {
  name: "selenium-build:build",
  description: "Pre-renders your app into a bunch of static html pages",
  works: "insideProject",
  availableOptions: [EnvOpt, OutOpt, PathOpt, FlavorOpt, StdOpt, HostOpt, PortOpt],
  run: function(cmdOpts, rawArgs) {
    var root;
    root = this.project.root;
    cmdOpts.buildRoutes = require(path.join(root, cmdOpts.buildRoutes));
    return new Selenium({
      ui: this.ui,
      analytics: this.analytics,
      project: this.project
    }).run(cmdOpts).then((function(_this) {
      return function() {
        return _this.ui.write("Your app has been built");
      };
    })(this));
  }
};
