// Generated by CoffeeScript 1.10.0
module.exports = {
  name: "selenium-build:init",
  description: "Setups the server which will handle selenium building",
  works: "insideProject",
  availableOptions: [],
  run: function(cmdOpts, rawArgs) {
    return new this.tasks.GenerateFromBlueprint({
      ui: this.ui,
      analytics: this.analytics,
      project: this.project,
      testing: this.testing,
      settings: this.settings
    }).run({
      args: ["server"]
    });
  }
};
